## Quick check any physics parameters for a single file

In [2]:
%matplotlib widget


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os, sys, pathlib, shlex, subprocess
import xbout
import scipy
import xhermes
from xhermes import *


sys.path.append(r"/users/jpm590/2dspace/post-processing/sdtools/")


from hermes3.utils import *


from hermes3.fluxes import *
from hermes3.case_db import *
from hermes3.load import *
from hermes3.named_selections import *
from hermes3.plotting import *
from hermes3.grid_fields import *
from hermes3.accessors import *
from hermes3.selectors import *

%load_ext autoreload
%autoreload 2
print("Done")

Done

In [3]:
db = CaseDB(
    case_dir = r"/users/jpm590/scratch/",
    # grid_dir = r"/users/jpm590/2dspace/hermes-3/build-mc-master"
    grid_dir = r"/users/jpm590/neutralrun/hermes-3/master"

)

toload = [
    # dict(name="source_guess", id="260112-cdn-46895-david-param", unnormalise_geom = True, use_xhermes = True, squash = True),
    # dict(name="david_param", id="260105-cdn-46895-david-param", unnormalise_geom = True, use_xhermes = True, squash = True),
    # dict(name="nowallpump_2e21", id="260207-cdn-46895-nowallpump_2e21", unnormalise_geom = True, use_xhermes = True, squash = True),
    # dict(name="nowallpump_1e21", id="260207-cdn-46895-nowallpump_1e21", unnormalise_geom = True, use_xhermes = True, squash = False),
    # dict(name="nowallpump_1e21_decayBC", id="260207-cdn-46895-nowallpump_decayBC_1e21", unnormalise_geom = True, use_xhermes = True, squash = False),
    dict(name="nowallpump_1e21_limiterOFF", id="260217-cdn-46895-nowallpump_limiterOff_1e21", unnormalise_geom = True, use_xhermes = True, squash = True),
    # dict(name="wallRecyON_1e21", id="260213-cdn-46895-wallRecyON_1e21", unnormalise_geom = True, use_xhermes = True, squash = True),


    # dict(name="new_grid", id="251210-cdn-46895", unnormalise_geom = True, use_xhermes = True, squash = True),
    # dict(name="original", id="251007-2D-MASTU", unnormalise_geom = True, use_xhermes = True, squash = True)
    

]
cs = {}
for case in toload:
    cs[case["name"]] = db.load_case_2D(case["id"], use_squash = case["squash"], verbose = True)
    # cs[case["name"]] = db.load_case_2D(case["id"], verbose = True)

    cs[case["name"]].extract_2d_tokamak_geometry()

/users/jpm590/workspace/hermes-3/venv/lib/python3.12/site-packages/boutdata/data.py:765: AlwaysWarning: While building x, y, z coordinate arrays, an exception occured: [Errno 2] No such file or directory: '"CDN_46895_260129_nowallpump_1e21.nc"'
Evaluating non-scalar options not available
  alwayswarn(

- Reading case 260217-cdn-46895-nowallpump_limiterOff_1e21
-----------------------
- Looking for squash file
- Squash file found. squash date 02/23/2026, 23:35:19, dmp file date 02/23/2026, 23:17:54

/users/jpm590/workspace/hermes-3/venv/lib/python3.12/site-packages/xbout/load.py:1124: UserWarning: Will drop all variables containing the dimensions 'closed_wall' because they are not recognised
  warn(

Unnormalising with xHermes

In [1]:
### Check meta data
m = cs["nowallpump_1e21_limiterOFF"].ds.metadata
# m
ds = cs["nowallpump_1e21_limiterOFF"].ds
# ds

NameError: name 'cs' is not defined

### Calculate the total power source
By `Pd+_src` + `Pe_src` times dv

Energy = 3/2 * pressure * volume 

`P_src` are in per second. So it's Power = 3/2 * P_src * dv

In [10]:

######
ds = cs["nowallpump_2e21"].ds.isel(t=-1)
total_press = ds["Pd+_src"].values + ds["Pe_src"].values + ds["Pd_src"].values
power2 = 3/2 * (ds["Pd+_src"].values + ds["Pe_src"].values + ds["Pd_src"].values) * ds["dv"].values
power2 = np.sum(power2)
print(f"Total power source = {power2}")

Total power source = 1001624.20689549

In [ ]:
#######

ds = cs["nowallpump_1e21_limiterOFF"].ds.isel(t=-1)

nparticles = (ds["Sd_src"].values) * ds["dv"].values
nparticles = np.sum(nparticles)
print(f"Total number of particles = {nparticles}")
#######

# ds = cs["nowallpump_1e21_decayBC"].ds.isel(t=-1)

# nparticles = (ds["Sd_src"].values) * ds["dv"].values
# nparticles = np.sum(nparticles)
# print(f"Total number of particles = {nparticles}")
# #######

# ds = cs["nowallpump_2e21"].ds.isel(t=-1)
# nparticles = (ds["Sd_src"].values) * ds["dv"].values
# nparticles = np.sum(nparticles)
# print(f"Total number of particles = {nparticles}")

#####

Total number of particles = 9.999999999999999e+20

## Calculate volume

Get the volume of the region you want.

You could possibly choose ([reference](https://github.com/mikekryjak/sdtools/blob/4242b6f0a55edf66d0b6e6f706bb7dc8515eb143/hermes3/deprecated/stuff.py#L155)): 
```python 
    core = ds.hermesm.select_region("core_edge")
    sol = ds.hermesm.select_region("sol_edge")
    pfr = ds.hermesm.select_region("pfr_edge")
    domain = ds.hermesm.select_region("all_noguards")
    domain_volume = domain["dv"].values.sum()
```
When you change a grid, the core volume is changed as well, therefore check "core_edge"

In [5]:
ds = cs["nowallpump_1e21_limiterOFF"].ds.isel(t=-1)

domain = ds.hermesm.select_region("core_edge")
domain_volume = domain["dv"].values.sum()
print(domain_volume)

#####
# ds = cs["nowallpump_1e21"].ds.isel(t=-1)

# domain = ds.hermesm.select_region("core_edge")
# domain_volume = domain["dv"].values.sum()
# print(domain_volume)

0.2968858850770253

## Check the position of source and pump
Polygon plot

In [1]:

ds = cs["wallRecyON_1e21"].ds.isel(t=-1)
fig, ax = plt.subplots(1,3 , figsize=(12,6))
ds["Sd_src" ].bout.polygon(ax = ax[0], cmap = "Spectral_r", antialias = True )
ds["Sd_pump" ].bout.polygon(ax = ax[1], cmap = "Spectral_r", antialias = True, )
ds["is_pump" ].bout.polygon(ax = ax[2], cmap = "Spectral_r", antialias = True, )

print()
plt.tight_layout()

NameError: name 'cs' is not defined

## Find the first core ring
The fuel is fuelling in the first core ring, so you should find the correct normalised position for fuelling function in input file.

```python
source = H(x) * H({first core ring} - x) * pressure_source
```

Below `sep` shows the position of the separatrix. `Srad` is the real distance from the separatrix (-: core, +: Sol). Note that `Srad` is in the cell center, while the real separatrix is on the boundary.

To get the normalised core ring position `x`, take `x` by cumulatively summing up the dx (width of each cell). Then normalised it by dividing max value.

The value you should take is the `x` where `Pe_src` is non-zero (1st core ring)

Also check where the target_recycling is on

In [9]:
########
#
# Check by Radial data
#
#######

ds = cs["nowallpump_1e21_limiterOFF"].ds.isel(t=-1)
df = get_1d_radial_data(ds, params = ["dx", "Pd_src","Pe_src","Pd+_src", "Sd_src", "Sd+_src" "Sd_pump", "Sd_target_recycle", "Sd_wall_recycle","Nd+"], region = "omp")

df["x"] = df["dx"].cumsum()
# x is in the center of the cell
df["x"] = df["x"]/df["x"].max()
df
# use the first 0.08

Parameter Sd+_srcSd_pump not found
Parameter Sd_wall_recycle not found

,t,total_poloidal_distance,zeta,dr,dx,Pd_src,Pe_src,Pd+_src,Sd_src,Sd_target_recycle,Nd+,Srad,sep,x
0,0.104421,3.831418,3.141593,0.007483,0.002440,0.000000,1.122750e+06,1.122750e+06,0.000000e+00,0.0,1.263401e+19,-0.058898,0,0.071421
1,0.104421,3.943389,3.141593,0.006791,0.002215,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.261586e+19,-0.051761,0,0.136254
2,0.104421,4.049806,3.141593,0.006145,0.002003,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.259039e+19,-0.045293,0,0.194888
3,0.104421,4.150752,3.141593,0.005542,0.001805,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.255872e+19,-0.039449,0,0.247709
4,0.104421,4.246313,3.141593,0.004980,0.001619,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.252280e+19,-0.034188,0,0.295104
5,0.104421,4.336584,3.141593,0.004459,0.001447,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.248506e+19,-0.029469,0,0.337462
6,0.104421,4.421685,3.141593,0.003977,0.001288,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.244719e+19,-0.025251,0,0.375170
7,0.104421,4.501782,3.141593,0.003534,0.001143,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.240939e+19,-0.021496,0,0.408616
8,0.104421,4.577099,3.141593,0.003131,0.001010,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.237035e+19,-0.018164,0,0.438186
9,0.104421,4.647935,3.141593,0.002767,0.000891,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.232766e+19,-0.015215,0,0.464269
10,0.104421,4.714687,3.141593,0.002442,0.000785,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.227856e+19,-0.012611,0,0.487252
11,0.104421,4.777892,3.141593,0.002157,0.000693,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.222128e+19,-0.010311,0,0.507523
12,0.104421,4.838276,3.141593,0.001913,0.000613,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.215537e+19,-0.008276,0,0.525468
13,0.104421,4.896849,3.141593,0.001709,0.000547,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.208220e+19,-0.006465,0,0.541476
14,0.104421,4.955097,3.141593,0.001545,0.000494,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.200374e+19,-0.004838,0,0.555934
15,0.104421,5.015426,3.141593,0.001423,0.000454,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.192149e+19,-0.003354,0,0.569229
16,0.104421,5.082561,3.141593,0.001342,0.000428,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.183605e+19,-0.001972,0,0.581749
17,0.104421,5.171179,3.141593,0.001302,0.000415,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.174706e+19,-0.000650,0,0.593882
18,0.104421,NaN,3.141593,0.001300,0.000413,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.165344e+19,0.000650,1,0.605983
19,0.104421,NaN,3.141593,0.001322,0.000420,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.155414e+19,0.001961,0,0.618277
20,0.104421,NaN,3.141593,0.001366,0.000433,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.144862e+19,0.003305,0,0.630961
21,0.104421,NaN,3.141593,0.001430,0.000453,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.133659e+19,0.004703,0,0.644228
22,0.104421,NaN,3.141593,0.001517,0.000480,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.121771e+19,0.006177,0,0.658271
23,0.104421,NaN,3.141593,0.001624,0.000513,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.109195e+19,0.007747,0,0.673287
24,0.104421,NaN,3.141593,0.001753,0.000553,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.095979e+19,0.009436,0,0.689469
25,0.104421,NaN,3.141593,0.001904,0.000599,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.082242e+19,0.011265,0,0.707010
26,0.104421,NaN,3.141593,0.002078,0.000652,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.068189e+19,0.013256,0,0.726107
27,0.104421,NaN,3.141593,0.002273,0.000712,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.054122e+19,0.015431,0,0.746952
28,0.104421,NaN,3.141593,0.002492,0.000779,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.040446e+19,0.017814,0,0.769741
29,0.104421,NaN,3.141593,0.002733,0.000852,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.027661e+19,0.020426,0,0.794668
30,0.104421,NaN,3.141593,0.002998,0.000931,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.016350e+19,0.023291,0,0.821926
31,0.104421,NaN,3.141593,0.003287,0.001018,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.007150e+19,0.026434,0,0.851711
32,0.104421,NaN,3.141593,0.003601,0.001111,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.000678e+19,0.029879,0,0.884216
33,0.104421,NaN,3.141593,0.003941,0.001210,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,9.973722e+18,0.033650,0,0.919637
34,0.104421,NaN,3.141593,0.004307,0.001316,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.0,9.971561e+18,0.037774,0,0.958167
35,0.104421,NaN,3.141593,0.004701,0.001429,55608.891306,0.000000e+00,0.000000e+00,1.735417e+23,0.0,9.987560e+18,0.042278,0,1.000000

In [4]:
########
#
# Check by poloidal data
#
#######
ds = cs["nowallpump_1e21_limiterOFF"].ds.isel(t=-1)

df = get_1d_poloidal_data(ds, params = ["dx", "Pd_src","Pe_src",
                                        "Pd+_src", "Sd_src", "Sd+_src" "Sd_pump", 
                                        "Sd_target_recycle", "Sd_wall_recycle", ], region = "outer_lower", sepadd=19)

df["x"] = df["dx"].cumsum()
# x is in the center of the cell
df["x"] = df["x"]/df["x"].max()
df
# use the first 0.08

Parameter Sd+_srcSd_pump not found
Parameter Sd_wall_recycle not found

,R,Z,dpol,Bxy,Bpxy,dx,Pd_src,Pe_src,Pd+_src,Sd_src,Sd_target_recycle,dpar,Spol,Spar,x
0,1.438092,0.000000,0.078896,0.421092,0.210289,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.157985,0.000000,0.000000,0.015152
1,1.438092,-0.039376,0.078896,0.421092,0.210289,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.157985,0.039448,0.078992,0.030303
2,1.427459,-0.116922,0.076737,0.430934,0.224982,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.146982,0.116185,0.225975,0.045455
3,1.410629,-0.189961,0.073402,0.445227,0.244739,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.133533,0.189587,0.359507,0.060606
4,1.393063,-0.259889,0.071034,0.455695,0.256550,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.126173,0.260620,0.485680,0.075758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,1.411894,-1.753089,0.010046,0.377358,0.065705,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.057694,2.353208,10.102618,0.939394
62,1.420908,-1.754602,0.008224,0.375137,0.066271,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.046551,2.361432,10.149169,0.954545
63,1.428122,-1.755667,0.006342,0.373380,0.066718,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.035493,2.367774,10.184662,0.969697
64,1.433445,-1.756369,0.004373,0.372097,0.067045,0.001675,0.0,0.0,0.0,0.0,0.000000e+00,0.024269,2.372147,10.208931,0.984848
65,1.436773,-1.756771,0.002305,0.371300,0.067249,0.001675,0.0,0.0,0.0,0.0,6.428463e+24,0.012724,2.374451,10.221655,1.000000